SET(OPENNURBS_INCLUDES
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_3dm_attributes.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_3dm.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_3dm_properties.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_3dm_settings.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_annotation2.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_annotation.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_arccurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_arc.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_archive.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_array_defs.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_array.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_base32.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_base64.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_beam.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_bezier.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_bitmap.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_bounding_box.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_box.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_brep.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_circle.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_color.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_compress.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_cone.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_crc.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_curve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_curveonsurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_curveproxy.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_cylinder.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_defines.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_detail.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_dimstyle.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_dll_resource.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_ellipse.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_error.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_evaluate_nurbs.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_extensions.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_font.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_fpoint.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_fsp_defs.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_fsp.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_geometry.h
	#include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_gl.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_group.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_hatch.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_hsort_template.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_instance.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_intersect.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_knot.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_layer.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_light.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_linecurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_line.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_linestyle.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_linetype.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_lookup.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_mapchan.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_massprop.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_material.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_math.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_matrix.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_memory.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_mesh.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_nurbscurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_nurbssurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_object.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_object_history.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_objref.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_offsetsurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_optimize.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_plane.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_planesurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_pluginlist.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_pointcloud.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_pointgeometry.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_pointgrid.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_point.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_polycurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_polyedgecurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_polylinecurve.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_polyline.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_qsort_template.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_quaternion.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_rand.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_rendering.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_revsurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_rtree.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_sphere.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_string.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_sumsurface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_surface.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_surfaceproxy.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_system.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_textlog.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_texture.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_texture_mapping.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_torus.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_unicode.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_userdata.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_uuid.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_version.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_viewport.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_workspace.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_xform.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_x.h
	include/pcl/${SUBSYS_NAME}/openNURBS/opennurbs_zlib.h
	include/pcl/${SUBSYS_NAME}/openNURBS/crc32.h
	include/pcl/${SUBSYS_NAME}/openNURBS/deflate.h
	include/pcl/${SUBSYS_NAME}/openNURBS/inffast.h
	include/pcl/${SUBSYS_NAME}/openNURBS/inffixed.h
	include/pcl/${SUBSYS_NAME}/openNURBS/inflate.h
	include/pcl/${SUBSYS_NAME}/openNURBS/inftrees.h
	include/pcl/${SUBSYS_NAME}/openNURBS/trees.h
	include/pcl/${SUBSYS_NAME}/openNURBS/zconf.h
	include/pcl/${SUBSYS_NAME}/openNURBS/zlib.h
	include/pcl/${SUBSYS_NAME}/openNURBS/zutil.h)

SET(	OPENNURBS_SOURCES
	src/openNURBS/opennurbs_3dm_attributes.cpp
	src/openNURBS/opennurbs_3dm_properties.cpp
	src/openNURBS/opennurbs_3dm_settings.cpp
	src/openNURBS/opennurbs_annotation2.cpp
	src/openNURBS/opennurbs_annotation.cpp
	src/openNURBS/opennurbs_arc.cpp
	src/openNURBS/opennurbs_arccurve.cpp
	src/openNURBS/opennurbs_archive.cpp
	src/openNURBS/opennurbs_array.cpp
	src/openNURBS/opennurbs_base32.cpp
	src/openNURBS/opennurbs_base64.cpp
	src/openNURBS/opennurbs_basic.cpp
	src/openNURBS/opennurbs_beam.cpp
	src/openNURBS/opennurbs_bezier.cpp
	src/openNURBS/opennurbs_beziervolume.cpp
	src/openNURBS/opennurbs_bitmap.cpp
	src/openNURBS/opennurbs_bounding_box.cpp
	src/openNURBS/opennurbs_box.cpp
	src/openNURBS/opennurbs_brep.cpp
	src/openNURBS/opennurbs_brep_extrude.cpp
	src/openNURBS/opennurbs_brep_io.cpp
	src/openNURBS/opennurbs_brep_isvalid.cpp
	src/openNURBS/opennurbs_brep_region.cpp
	src/openNURBS/opennurbs_brep_tools.cpp
	src/openNURBS/opennurbs_brep_v2valid.cpp
	src/openNURBS/opennurbs_circle.cpp
	src/openNURBS/opennurbs_color.cpp
	src/openNURBS/opennurbs_compress.cpp
	src/openNURBS/opennurbs_cone.cpp
	src/openNURBS/opennurbs_crc.cpp
	src/openNURBS/opennurbs_curve.cpp
	src/openNURBS/opennurbs_curveonsurface.cpp
	src/openNURBS/opennurbs_curveproxy.cpp
	src/openNURBS/opennurbs_cylinder.cpp
	src/openNURBS/opennurbs_defines.cpp
	src/openNURBS/opennurbs_detail.cpp
	src/openNURBS/opennurbs_dimstyle.cpp
	src/openNURBS/opennurbs_dll.cpp
	src/openNURBS/opennurbs_ellipse.cpp
	src/openNURBS/opennurbs_embedded_file.cpp
	src/openNURBS/opennurbs_error.cpp
	src/openNURBS/opennurbs_error_message.cpp
	src/openNURBS/opennurbs_evaluate_nurbs.cpp
	src/openNURBS/opennurbs_extensions.cpp
	src/openNURBS/opennurbs_font.cpp
	src/openNURBS/opennurbs_fsp.cpp
	src/openNURBS/opennurbs_geometry.cpp
	#src/openNURBS/opennurbs_gl.cpp
	src/openNURBS/opennurbs_group.cpp
	src/openNURBS/opennurbs_hatch.cpp
	src/openNURBS/opennurbs_instance.cpp
	src/openNURBS/opennurbs_intersect.cpp
	src/openNURBS/opennurbs_knot.cpp
	src/openNURBS/opennurbs_layer.cpp
	src/openNURBS/opennurbs_light.cpp
	src/openNURBS/opennurbs_line.cpp
	src/openNURBS/opennurbs_linecurve.cpp
	src/openNURBS/opennurbs_linetype.cpp
	src/openNURBS/opennurbs_lookup.cpp
	src/openNURBS/opennurbs_massprop.cpp
	src/openNURBS/opennurbs_material.cpp
	src/openNURBS/opennurbs_math.cpp
	src/openNURBS/opennurbs_matrix.cpp
	src/openNURBS/opennurbs_memory.c
	src/openNURBS/opennurbs_memory_util.c
	src/openNURBS/opennurbs_mesh.cpp
	src/openNURBS/opennurbs_mesh_ngon.cpp
	src/openNURBS/opennurbs_mesh_tools.cpp
	src/openNURBS/opennurbs_morph.cpp
	src/openNURBS/opennurbs_nurbscurve.cpp
	src/openNURBS/opennurbs_nurbssurface.cpp
	src/openNURBS/opennurbs_nurbsvolume.cpp
	src/openNURBS/opennurbs_object.cpp
	src/openNURBS/opennurbs_object_history.cpp
	src/openNURBS/opennurbs_objref.cpp
	src/openNURBS/opennurbs_offsetsurface.cpp
	src/openNURBS/opennurbs_optimize.cpp
	src/openNURBS/opennurbs_plane.cpp
	src/openNURBS/opennurbs_planesurface.cpp
	src/openNURBS/opennurbs_pluginlist.cpp
	src/openNURBS/opennurbs_pointcloud.cpp
	src/openNURBS/opennurbs_point.cpp
	src/openNURBS/opennurbs_pointgeometry.cpp
	src/openNURBS/opennurbs_pointgrid.cpp
	src/openNURBS/opennurbs_polycurve.cpp
	src/openNURBS/opennurbs_polyedgecurve.cpp
	src/openNURBS/opennurbs_polyline.cpp
	src/openNURBS/opennurbs_polylinecurve.cpp
	src/openNURBS/opennurbs_precompiledheader.cpp
	src/openNURBS/opennurbs_quaternion.cpp
	src/openNURBS/opennurbs_rand.cpp
	src/openNURBS/opennurbs_revsurface.cpp
	src/openNURBS/opennurbs_rtree.cpp
	src/openNURBS/opennurbs_sort.cpp
	src/openNURBS/opennurbs_sphere.cpp
	src/openNURBS/opennurbs_string.cpp
	src/openNURBS/opennurbs_sum.cpp
	src/openNURBS/opennurbs_sumsurface.cpp
	src/openNURBS/opennurbs_surface.cpp
	src/openNURBS/opennurbs_surfaceproxy.cpp
	src/openNURBS/opennurbs_textlog.cpp
	src/openNURBS/opennurbs_torus.cpp
	src/openNURBS/opennurbs_unicode.cpp
	src/openNURBS/opennurbs_userdata.cpp
	src/openNURBS/opennurbs_uuid.cpp
	src/openNURBS/opennurbs_viewport.cpp
	src/openNURBS/opennurbs_workspace.cpp
	src/openNURBS/opennurbs_wstring.cpp
	src/openNURBS/opennurbs_xform.cpp
	src/openNURBS/opennurbs_zlib.cpp
	src/openNURBS/opennurbs_zlib_memory.cpp
	src/openNURBS/adler32.c
	src/openNURBS/compress.c
	src/openNURBS/crc32.c
	src/openNURBS/deflate.c
	src/openNURBS/infback.c
	src/openNURBS/inffast.c
	src/openNURBS/inflate.c
	src/openNURBS/inftrees.c
	src/openNURBS/trees.c
	src/openNURBS/uncompr.c
	src/openNURBS/zutil.c)
		
