# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale Issue or Pull Request is closed
# 10000 days until https://github.com/probot/stale/issues/79 is fixed
daysUntilClose: 10000
# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - "status: needs review"
  - "status: needs testing"
  - "status: needs decision"
  - "status: ready to merge"
# Label to use when marking as stale
staleLabel: "status: stale"
# Comment to post when marking as stale. Set to `false` to disable
markComment: |
  This pull request has been automatically marked as stale because it hasn't had
  any activity in the past 60 days. Commenting or adding a new commit to the
  pull request will revert this.
  
  Come back whenever you have time. We look forward to your contribution.
# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false
# Comment to post when closing a stale Issue or Pull Request. Set to `false` to disable
closeComment: false
# Limit to only `issues` or `pulls`
only: pulls
