/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper.pcl;

public class PointCloud_Normal {
  private long swigCPtr;
  private boolean swigCMemOwn;

  public PointCloud_Normal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointCloud_Normal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapper.pcl_moduleJNI.delete_pcl_PointCloud_Normal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointCloud_Normal() {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_Normal__SWIG_0(), true);
  }

  public PointCloud_Normal(wrapper.pcl.PointCloud_Normal pc) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_Normal__SWIG_1(wrapper.pcl.PointCloud_Normal.getCPtr(pc), pc), true);
  }

  public PointCloud_Normal(wrapper.pcl.PointCloud_Normal pc, wrapper.vector_int indices) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_Normal__SWIG_3(wrapper.pcl.PointCloud_Normal.getCPtr(pc), pc, wrapper.vector_int.getCPtr(indices), indices), true);
  }

  public PointCloud_Normal(long width_, long height_, wrapper.pcl.Normal value_) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_Normal__SWIG_4(width_, height_, wrapper.pcl.Normal.getCPtr(value_), value_), true);
  }

  public PointCloud_Normal(long width_, long height_) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_Normal__SWIG_5(width_, height_), true);
  }

  public wrapper.pcl.PointCloud_Normal Add_To_Self(wrapper.pcl.PointCloud_Normal rhs) {
    return new wrapper.pcl.PointCloud_Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_Add_To_Self(swigCPtr, this, wrapper.pcl.PointCloud_Normal.getCPtr(rhs), rhs), true);
  }

  public wrapper.pcl.PointCloud_Normal Add(wrapper.pcl.PointCloud_Normal rhs) {
    return new wrapper.pcl.PointCloud_Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_Add(swigCPtr, this, wrapper.pcl.PointCloud_Normal.getCPtr(rhs), rhs), true);
  }

  public wrapper.pcl.Normal at(int column, int row) {
    return new wrapper.pcl.Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_at__SWIG_0(swigCPtr, this, column, row), false);
  }

  public wrapper.pcl.Normal at(long column, long row) {
    return new wrapper.pcl.Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_at__SWIG_2(swigCPtr, this, column, row), false);
  }

  public boolean isOrganized() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_isOrganized(swigCPtr, this);
  }

  public wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator begin() {
    return new wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_begin__SWIG_0(swigCPtr, this), true);
  }

  public wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator end() {
    return new wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_end__SWIG_0(swigCPtr, this), true);
  }

  public long size() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_size(swigCPtr, this);
  }

  public void reserve(long n) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_empty(swigCPtr, this);
  }

  public void resize(long n) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_resize(swigCPtr, this, n);
  }

  public wrapper.pcl.Normal at(long n) {
    return new wrapper.pcl.Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_at__SWIG_4(swigCPtr, this, n), false);
  }

  public wrapper.pcl.Normal front() {
    return new wrapper.pcl.Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_front__SWIG_0(swigCPtr, this), false);
  }

  public wrapper.pcl.Normal back() {
    return new wrapper.pcl.Normal(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_back__SWIG_0(swigCPtr, this), false);
  }

  public void push_back(wrapper.pcl.Normal pt) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_push_back(swigCPtr, this, wrapper.pcl.Normal.getCPtr(pt), pt);
  }

  public wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator insert(wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator position, wrapper.pcl.Normal pt) {
    return new wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_insert__SWIG_0(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator.getCPtr(position), wrapper.pcl.Normal.getCPtr(pt), pt), true);
  }

  public void insert(wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator position, long n, wrapper.pcl.Normal pt) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_insert__SWIG_1(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator.getCPtr(position), n, wrapper.pcl.Normal.getCPtr(pt), pt);
  }

  public wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator erase(wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator position) {
    return new wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_erase__SWIG_0(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator.getCPtr(position)), true);
  }

  public wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator erase(wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator first, wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator last) {
    return new wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_erase__SWIG_1(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator.getCPtr(first), wrapper.SWIGTYPE_p_pcl__PointCloudT_pcl__Normal_t__VectorType__iterator.getCPtr(last)), true);
  }

  public void swap(wrapper.pcl.PointCloud_Normal rhs) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_swap(swigCPtr, this, wrapper.pcl.PointCloud_Normal.getCPtr(rhs), rhs);
  }

  public void clear() {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_clear(swigCPtr, this);
  }

  public wrapper.pcl.PointCloud_Normal makeShared() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_makeShared(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.pcl.PointCloud_Normal(cPtr, true);
  }

  public void setHeader(wrapper.SWIGTYPE_p_pcl__PCLHeader value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_header_set(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PCLHeader.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_pcl__PCLHeader getHeader() {
    return new wrapper.SWIGTYPE_p_pcl__PCLHeader(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_header_get(swigCPtr, this), true);
  }

  public void setPoints(wrapper.SWIGTYPE_p_std__vectorT_pcl__Normal_Eigen__aligned_allocatorT_pcl__Normal_t_t value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_points_set(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__Normal_Eigen__aligned_allocatorT_pcl__Normal_t_t.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__Normal_Eigen__aligned_allocatorT_pcl__Normal_t_t getPoints() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_points_get(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.SWIGTYPE_p_std__vectorT_pcl__Normal_Eigen__aligned_allocatorT_pcl__Normal_t_t(cPtr, false);
  }

  public void setWidth(long value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_height_get(swigCPtr, this);
  }

  public void setIs_dense(boolean value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_is_dense_set(swigCPtr, this, value);
  }

  public boolean getIs_dense() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_is_dense_get(swigCPtr, this);
  }

  public void setSensor_origin_(wrapper.SWIGTYPE_p_Eigen__Vector4f value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_sensor_origin__set(swigCPtr, this, wrapper.SWIGTYPE_p_Eigen__Vector4f.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_Eigen__Vector4f getSensor_origin_() {
    return new wrapper.SWIGTYPE_p_Eigen__Vector4f(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_sensor_origin__get(swigCPtr, this), true);
  }

  public void setSensor_orientation_(wrapper.SWIGTYPE_p_Eigen__Quaternionf value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_sensor_orientation__set(swigCPtr, this, wrapper.SWIGTYPE_p_Eigen__Quaternionf.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_Eigen__Quaternionf getSensor_orientation_() {
    return new wrapper.SWIGTYPE_p_Eigen__Quaternionf(wrapper.pcl_moduleJNI.pcl_PointCloud_Normal_sensor_orientation__get(swigCPtr, this), true);
  }

}
