/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper.pcl;

public class PointXYZ {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PointXYZ(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointXYZ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapper.pcl_moduleJNI.delete_pcl_PointXYZ(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointXYZ() {
    this(wrapper.pcl_moduleJNI.new_pcl_PointXYZ__SWIG_0(), true);
  }

  public PointXYZ(float _x, float _y, float _z) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointXYZ__SWIG_1(_x, _y, _z), true);
  }

  public void setX(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZ_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZ_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZ_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZ_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZ_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZ_z_get(swigCPtr, this);
  }

  public void setData(wrapper.SWIGTYPE_p_float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZ_data_set(swigCPtr, this, wrapper.SWIGTYPE_p_float.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_float getData() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointXYZ_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.SWIGTYPE_p_float(cPtr, false);
  }

}
