resources:
  containers:
    - container: fmt
      image: pointcloudlibrary/fmt

jobs:
  - job: formatting
    displayName: Check code formatting
    pool:
      vmImage: 'Ubuntu 16.04'
    container: fmt
    steps:
      - script: ./.dev/format.sh $(which clang-format-8) .
        displayName: 'Run clang-format'
      - script: git diff > formatting.patch
        displayName: 'Compute diff'
      - script: cat formatting.patch
        displayName: 'Show diff'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: 'formatting.patch'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy diff to staging directory'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: formatting
        displayName: 'Publish diff'
      - script: "[ ! -s formatting.patch ]"
        displayName: 'Set job exit status'
