/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itseez_peopledemo_BodyPartsRecognizer */

#ifndef _Included_com_itseez_peopledemo_BodyPartsRecognizer
#define _Included_com_itseez_peopledemo_BodyPartsRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itseez_peopledemo_BodyPartsRecognizer
 * Method:    cacheIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_peopledemo_BodyPartsRecognizer_cacheIds
  (JNIEnv *, jclass);

/*
 * Class:     com_itseez_peopledemo_BodyPartsRecognizer
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_peopledemo_BodyPartsRecognizer_create
  (JNIEnv *, jobject);

/*
 * Class:     com_itseez_peopledemo_BodyPartsRecognizer
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_peopledemo_BodyPartsRecognizer_free
  (JNIEnv *, jobject);

/*
 * Class:     com_itseez_peopledemo_BodyPartsRecognizer
 * Method:    recognize
 * Signature: (Lcom/itseez/peopledemo/RGBDImage;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_itseez_peopledemo_BodyPartsRecognizer_recognize
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
