/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itseez_onirec_CaptureThreadManager */

#ifndef _Included_com_itseez_onirec_CaptureThreadManager
#define _Included_com_itseez_onirec_CaptureThreadManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itseez_onirec_CaptureThreadManager
 * Method:    imageBufferToBitmap
 * Signature: (Ljava/nio/ByteBuffer;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_itseez_onirec_CaptureThreadManager_imageBufferToBitmap
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_itseez_onirec_CaptureThreadManager
 * Method:    depthBufferToBitmap
 * Signature: (Ljava/nio/ShortBuffer;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_itseez_onirec_CaptureThreadManager_depthBufferToBitmap
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
