/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_onirec_grab_NativeBuffer */

#ifndef _Included_org_pointclouds_onirec_grab_NativeBuffer
#define _Included_org_pointclouds_onirec_grab_NativeBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pointclouds_onirec_grab_NativeBuffer
 * Method:    getPtr
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_pointclouds_onirec_grab_NativeBuffer_getPtr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_pointclouds_onirec_grab_NativeBuffer
 * Method:    fillBuffer
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_pointclouds_onirec_grab_NativeBuffer_fillBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
