/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper;

public class SWIGTYPE_p_p_char {
  private long swigCPtr;

  public SWIGTYPE_p_p_char(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_p_char() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_p_char obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

