/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itseez_bodyparts_Grabber */

#ifndef _Included_com_itseez_bodyparts_Grabber
#define _Included_com_itseez_bodyparts_Grabber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    cacheIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_bodyparts_Grabber_cacheIds
  (JNIEnv *, jclass);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_bodyparts_Grabber_free
  (JNIEnv *, jobject);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    createOpenNIGrabber
 * Signature: ()Lcom/itseez/peopledemo/Grabber;
 */
JNIEXPORT jobject JNICALL Java_com_itseez_bodyparts_Grabber_createOpenNIGrabber
  (JNIEnv *, jclass);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    createFileGrabber
 * Signature: (Ljava/lang/String;)Lcom/itseez/peopledemo/Grabber;
 */
JNIEXPORT jobject JNICALL Java_com_itseez_bodyparts_Grabber_createFileGrabber
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_itseez_bodyparts_Grabber_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    getFrame
 * Signature: (Lcom/itseez/peopledemo/RGBDImage;)V
 */
JNIEXPORT void JNICALL Java_com_itseez_bodyparts_Grabber_getFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_bodyparts_Grabber_start
  (JNIEnv *, jobject);

/*
 * Class:     com_itseez_bodyparts_Grabber
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itseez_bodyparts_Grabber_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
