name: clang-tidy

on: [push, pull_request]

jobs:
  tidy:
    runs-on: ubuntu-latest
    container:
      image: pointcloudlibrary/env:22.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Run clang-tidy
      run: |
          bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          cmake .
          run-clang-tidy-14.py -config='' -header-filter='.*' -fix
          git diff > tidy.patch
          cat tidy.patch
          [ ! -s tidy.patch ]

