name: clang-tidy

on: [push, pull_request]

jobs:
  tidy:
    runs-on: ubuntu-latest
    container:
      image: pointcloudlibrary/env:22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Run clang-tidy
      run: |
          bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang-14 -DCMAKE_C_COMPILER=/usr/bin/clang-14 . \
            -DBUILD_benchmarks=ON \
            -DBUILD_examples=ON \
            -DBUILD_simulation=ON \
            -DBUILD_global_tests=ON
        
          run-clang-tidy -header-filter='.*'
